import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TasksGen",
  description: "Generated by create next app",
  icons: "./assets/task.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-branco font-poppins text-preto">
        <div className='bg-teal-700 w-full p-4 flex flex-row items-center gap-2'>
          <img className="hover:shadow-cyan-300 hover:shadow-md duration-150 transition-shadow w-12" src="./assets/task.png" />
          <p className="text-violet-100 text-xl font-extralight">Bem vindo!</p>
        </div>
        {children}
      </body>
    </html>
  );
}
